# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import demo_pb2 as demo__pb2


class DemoStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetModelWithId = channel.unary_unary(
        '/demo.Demo/GetModelWithId',
        request_serializer=demo__pb2.ModelId.SerializeToString,
        response_deserializer=demo__pb2.Model.FromString,
        )


class DemoServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetModelWithId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DemoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetModelWithId': grpc.unary_unary_rpc_method_handler(
          servicer.GetModelWithId,
          request_deserializer=demo__pb2.ModelId.FromString,
          response_serializer=demo__pb2.Model.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'demo.Demo', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
