version: '3'

services:
  flask:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - .:/app
    command: ["uwsgi", "--ini", "app.ini"]

  grpc:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - .:/app
    ports:
      - ${GRPC_SERVER_PORT}:${GRPC_SERVER_PORT}
    command: ["python3", "GRPCServer.py"]

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 5000:80
    depends_on:
      - flask

  postgres:
    image: postgres:11.1
    ports:
       - "5555:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${PGDATA}
    volumes:
    - ${PSQL_VOLUME_PATH}:/var/lib/postgresql/data
