# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='demo.proto',
  package='demo',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\ndemo.proto\x12\x04\x64\x65mo\"\x15\n\x07ModelId\x12\n\n\x02id\x18\x01 \x02(\x05\"1\n\x05Model\x12\x12\n\ntext_value\x18\x01 \x02(\t\x12\x14\n\x0cselect_value\x18\x02 \x02(\t26\n\x04\x44\x65mo\x12.\n\x0eGetModelWithId\x12\r.demo.ModelId\x1a\x0b.demo.Model\"\x00')
)




_MODELID = _descriptor.Descriptor(
  name='ModelId',
  full_name='demo.ModelId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='demo.ModelId.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=41,
)


_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='demo.Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text_value', full_name='demo.Model.text_value', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='select_value', full_name='demo.Model.select_value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['ModelId'] = _MODELID
DESCRIPTOR.message_types_by_name['Model'] = _MODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelId = _reflection.GeneratedProtocolMessageType('ModelId', (_message.Message,), dict(
  DESCRIPTOR = _MODELID,
  __module__ = 'demo_pb2'
  # @@protoc_insertion_point(class_scope:demo.ModelId)
  ))
_sym_db.RegisterMessage(ModelId)

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), dict(
  DESCRIPTOR = _MODEL,
  __module__ = 'demo_pb2'
  # @@protoc_insertion_point(class_scope:demo.Model)
  ))
_sym_db.RegisterMessage(Model)



_DEMO = _descriptor.ServiceDescriptor(
  name='Demo',
  full_name='demo.Demo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=94,
  serialized_end=148,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetModelWithId',
    full_name='demo.Demo.GetModelWithId',
    index=0,
    containing_service=None,
    input_type=_MODELID,
    output_type=_MODEL,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEMO)

DESCRIPTOR.services_by_name['Demo'] = _DEMO

# @@protoc_insertion_point(module_scope)
